#include "Error.h"

namespace efs
{
	std::unordered_map<ErrorCode, std::string> ErrorCodeStrMap = {
	   {ErrorCode::NONE,std::string("NONE")},
	   {ErrorCode::E_OVERFLOW,std::string("E_OVERFLOW")},
	   {ErrorCode::E_BUFFER_SIZE,std::string("E_BUFFER_SIZE")},
	   {ErrorCode::E_NOT_FOUND,std::string("E_NOT_FOUND")},
	   {ErrorCode::E_UNKNOWN_TYPE,std::string("E_UNKNOWN_TYPE")},
	   {ErrorCode::E_NETWORK,std::string("E_NETWORK")},
	   {ErrorCode::E_PANIC,std::string("E_PANIC")},
	   {ErrorCode::E_MSG_UNKNOWN,std::string("E_MSG_UNKNOWN")},
	   {ErrorCode::E_LOGIN_USER_NOT_FOUND,std::string("E_LOGIN_USER_NOT_FOUND")},
	   {ErrorCode::E_LOGIN_WRONG_PASSWORD,std::string("E_LOGIN_WRONG_PASSWORD")},
	   {ErrorCode::E_USER_NOT_FOUND,std::string("E_USER_NOT_FOUND")},
	   {ErrorCode::E_GROUP_NOT_FOUND,std::string("E_GROUP_NOT_FOUND")},
	   {ErrorCode::E_SERIALIZE,std::string("E_SERIALIZE")},
	   {ErrorCode::E_DESERIALIZE,std::string("E_DESERIALIZE")},
	   {ErrorCode::E_FILE_OPEN,std::string("E_FILE_OPEN")},
	   {ErrorCode::E_FILE_RM,std::string("E_FILE_RM")},
	   {ErrorCode::E_FILE_MV,std::string("E_FILE_MV")},
	   {ErrorCode::E_FILE_MKDIR,std::string("E_FILE_MKDIR")},
	   {ErrorCode::E_FILE_LS,std::string("E_FILE_LS")},
	   {ErrorCode::E_FILE_WRITE,std::string("E_FILE_WRITE")},
	   {ErrorCode::E_FILE_READ,std::string("E_FILE_READ")},
	   {ErrorCode::E_FILE_EOF,std::string("E_FILE_EOF")},
	   {ErrorCode::E_FILE_PERMISSION,std::string("E_FILE_PERMISSION")},
	   {ErrorCode::E_FILE_NOT_FOUND,std::string("E_FILE_NOT_FOUND")},
	   {ErrorCode::E_FILE_TOO_MANY,std::string("E_FILE_TOO_MANY")},
	   {ErrorCode::E_FILE_PATH,std::string("E_FILE_PATH")},
	   {ErrorCode::E_FILE_PERM,std::string("E_FILE_PERM")},
	   {ErrorCode::E_FILE_SEEK,std::string("E_FILE_SEEK")},
	   {ErrorCode::E_FILE_TRUNCATE,std::string("E_FILE_TRUNCATE")},
	   {ErrorCode::E_FILE_INVALID_PATH,std::string("E_FILE_INVALID_PATH")},
	   {ErrorCode::E_FILE_UNKNOWN_TYPE,std::string("E_FILE_UNKNOWN_TYPE")},
	   {ErrorCode::E_FILE_EXIST,std::string("E_FILE_EXIST")},
	   {ErrorCode::E_DB_OPEN,std::string("E_DB_OPEN")},
	   {ErrorCode::E_DB_GET,std::string("E_DB_GET")},
	   {ErrorCode::E_DB_PUT,std::string("E_DB_PUT")},
	   {ErrorCode::E_DB_DEL,std::string("E_DB_DEL")},
	   {ErrorCode::E_TOKEN_ERROR,std::string("E_TOKEN_ERROR")},
	   {ErrorCode::E_CONFIG_ERROR,std::string("E_CONFIG_ERROR")},
	};
}
